### ISSUE TITLE
Listbox: Show a disclaimer when there are no search matches

### ISSUE THREAD

**Issue by johanlahti** [qlik-oss/nebula.js#1025]
## 🚀 Feature

Show a disclaimer in the Listbox when there are no search matches.
It should appear like in the old listbox (i.e. also in popovers). See below:

![image](https://user-images.githubusercontent.com/5780544/206198189-8168784d-8690-4503-87ac-683f2cea4eea.png)

### Motivation

Feature parity. https://jira.qlikdev.com/browse/QB-16970

**Comment by CostInCode** [comment]
The linked PR above implements the feature. See the screens below for both sense client and Nebula mashup.

<img width="601" alt="Screenshot 2023-03-10 at 09 36 12" src="https://user-images.githubusercontent.com/13185716/224266357-3aecf213-e1df-40c8-8e35-48a4f6783393.png">

<img width="354" alt="Screenshot 2023-03-10 at 09 45 11" src="https://user-images.githubusercontent.com/13185716/224268244-e8075f8c-a204-4c5e-a026-d8943fb2c8ee.png">
