### ISSUE TITLE
Type definition for nebula.js/sn-bar-chart

### ISSUE THREAD

**Issue by erYasar** [qlik-oss/nebula.js#1032]
Could you help me with the Type definition for nebula.js/sn-bar-chart.

error TS7016: Could not find a declaration file for module '@nebula.js/sn-bar-chart'. './node_modules/@nebula.js/sn-bar-chart/dist/sn-bar-chart.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/nebula.js__sn-bar-chart` if it exists or add a new declaration (.d.ts) file containing `declare module '@nebula.js/sn-bar-chart';`

**Comment by Caele** [comment]
Charts does not have type definitions at this point, will take this under consideration however.
