### ISSUE TITLE
Selections Bar shows hidden fields, native selection bar hides them

### ISSUE THREAD

**Issue by MarkFereday** [qlik-oss/nebula.js#1102]
## 🐛 Bug report

Selections Bar shows hidden fields, native selection bar hides them

### Steps to Reproduce

1. Include the selection bar in a mashup.
2. Data model has hidden fields
3. Make a selection in a hidden field
4. Selections bar should not show selections in a hidden field

### Expected behavior

Selections bar should not show hidden fields as per native behaviour.

### Actual behavior

Selections bar shows hidden fields, which is different to native behaviour.

### Versions

- nebula.js: (3.2.2)

**Comment by Caele** [comment]
Fix here: https://github.com/qlik-oss/nebula.js/pull/1094
Will be included in 3.3.0
