### ISSUE TITLE
Issue with object galaxy that passed into supernova function. 

### ISSUE THREAD

**Issue by borisPerlov** [qlik-oss/nebula.js#1103]
## 🐛 Bug report

Hi all : )

I use nebula.js to create an extension for Qlik Sense. 
I pass the galaxy object into the supernova function and according to [the tutoria](https://qlik.dev/libraries-and-tools/nebulajs/in-qlik-sense) l the object galaxy includes the navigation object but actually, the navigation object doesn't exist. 

### Steps to Reproduce

1. git clone https://github.com/borisPerlov/navigation_extension.git
2. npm i
3. npm run start
4. npm run build
5. open dev tools 
6. the debugger will stop in component and the object galaxy will be available but will not include navigation object

### Expected behavior

/* Contents of galaxy */ according to tutorial 
galaxy: {
  anything: {
    sense: {
      navigation,
      theme,
    },
  },
  deviceType,
  translator,
}

### Actual behavior

/* Contents of galaxy */ actually
galaxy: {
  anything: {
      //empty
  },
flags : {},
 translator : {}
}

### Versions

- "@nebula.js/stardust": "3.2.2"
- Platform: qlick sense
- Browser: chrome

### Additional context

![image](https://user-images.githubusercontent.com/49359486/222483017-f0569fc5-078d-4a90-ad3b-8f6b4f9803ae.png)

**Comment by Caele** [comment]
@borisPerlov Hey, thanks for the feedback.
The `sense` and subsequent `sense.navigation` object is actually only available when running your extensions inside sense.
That tutorial you link specifically states: "When a nebula.js extension is loaded in Qlik Sense it gets a set of useful tools passed into the supernova function."

The reasons for this is that the navigation API exposed by Sense is actually only relevant when your extension is placed on a sheet inside Sense. When rendering outside of Sense there are no sheets per se, and no specifically no navigation between sheets.

If you want your extension to utilize the navigation API please check for its existance.
