### ISSUE TITLE
@nebula.js/sn-map fails to compile. Can't resolve 'axios'

### ISSUE THREAD

**Issue by frankAOD** [qlik-oss/nebula.js#1173]
## 🐛 Bug report

Installing @nebula.js/sn-map and using with standard Stardust embed method results in compile error.

./node_modules/@nebula.js/sn-map/dist/sn-map.js:19969:14-30 - Error: Module not found: Error: Can't resolve 'axios' in '[path to project]\node_modules\@nebula.js\sn-map\dist'

### Steps to Reproduce

1. npm install @nebula.js/sn-map
2. implement stardust embed method per standard process.

### Versions

- enigma.js 2.11.0
- nebula.js.stardust 3.3.0
- nebula.js/sn-map 0.9.0

**Comment by Caele** [comment]
The map has axios as a peer dependency, make sure that is installed as well: https://github.com/qlik-oss/sn-map/blob/main/package.json#L90
