### ISSUE TITLE
Alternative measure/dimension selection unavailable

### ISSUE THREAD

**Issue by M1CK431** [qlik-oss/nebula.js#1318]
## 🐛 Bug report

On Qlik:
![image](https://github.com/qlik-oss/nebula.js/assets/31622263/5a0c5479-1c20-423d-bde3-a0e2b6d169d7)

With Nebula:
![image](https://github.com/qlik-oss/nebula.js/assets/31622263/fac38d41-d62b-4bae-824c-43694a11f445)

Nothing happens while clicking on the axis label of Nebula bar chart

### Steps to Reproduce

1. embed a bar chart with Nebula which has multiple measures
2. click on the axis label to choose the desired measure
3. nothing happens! 💥 

### Expected behavior

Ability to select the desired measure on axis label click, like in Qlik.

### Actual behavior

Nothing happens on axis label click.

### Versions
- nebula.js:
  - "@nebula.js/sn-bar-chart": "^1.33.0",
  - "@nebula.js/stardust": "^4.2.3",
- Platform: not relevant
- Browser: Chrome/114.0.0.0

**Comment by M1CK431** [comment]
any idea @Caele ?

**Comment by M1CK431** [comment]
After so many answers... I finally found a way to workaround this issue after reading this: https://community.qlik.com/t5/Integration-Extension-APIs/Engine-API-Get-Object-layout-for-an-Alternate-Dimension/td-p/1670667

The workaround is to implement a select yourself:
- options for the select can be obtained using `getProperties()` on the generic object then build an array with `[...qHyperCubeDef.qDimensions, ...qHyperCubeDef.qLayoutExclude.qHyperCubeDef.qDimensions]` to get all available dimensions
- the current dimension is in `qHyperCubeDef.qDimensions[0]` 
- for measures, remplace `qDimensions` by `qMeasures`
- dimensions labels are in `qDef.qFieldLabels[0]` but for measures labels 2 additional API calls are needed: `doc.getMeasure(id).then(qMeasure => qMeasure.getLayout())` (`id` is from `qLibraryId`) then label is in `qMeta.title`
- to change the current dimension/measure, use `applyPatches` method on the generic object as described in the discussion provided at the beginning of that comment.

Good luck...

**Comment by Caele** [comment]
This is due to the logic for the alternative dim/measure selection is done in the actual client UI, and not in the individual charts or Nebula. This exists on our roadmap, but continues to be pushed low. I currently have no timeline.

**Comment by xunziheng** [comment]
but it works well in capability api.

**Comment by xunziheng** [comment]
> but it works well in capability api.

excuse me @Caele , does Nebula team have plan to support this now?
