### ISSUE TITLE
Property panel not rendering in Qlik Sense Saas

### ISSUE THREAD

**Issue by mjunlim** [qlik-oss/nebula.js#1341]
## 🐛 Bug report

Property panel not rendering in Qlik Sense Saas.
```ext.js```
(A clear and concise description of what the bug is.)
When adding custom 

### Steps to Reproduce

1. Update ```ext.js``` with ```definition: { ... }``` (the definition code attached below)
2. Build and import as extension in Qlik

### Expected behavior

Should be able to see the property in the property panel.

### Actual behavior

Nothing is being rendered...

### Versions

- nebula.js: 4.4.0
- Platform: Mac
- Browser: chrome

### Additional context

The definition code in ```ext.js```
```
  definition: {
      type: "items",
      component: "accordion",
      items: {
        type: "items",
        component: "accordion",
        items: {
          settings: {
            uses: "settings",
            items: {
              MyNumProp: {
                type: "number",
                label: "Maximum",
                ref: "myproperties.max",
                defaultValue: "10.5"
              }
            }
          }
        }
      }
    }
```

**Comment by Caele** [comment]
Will have to refer to the qlik.dev help: https://qlik.dev/extend/property-panel-basics/ as the property panel is not a part of Nebula.
