### ISSUE TITLE
Allow for additional dependencies in nebula serve html

### ISSUE THREAD

**Issue by joelstransky** [qlik-oss/nebula.js#1419]
## 🚀 Feature

Add hooks or flags to `nebula serve` so that I can tell it to also include leonardo-ui css

### Motivation

Qlik Sense loads leonardo by default so compiling it into my extensions doesn't make sense just to view it in nebula hub.

### Additional context

commands/serve/web/index.html

**Comment by joelstransky** [comment]
Other discussions on this. https://community.qlik.com/t5/QlikView-Integrations/How-to-use-CSS-inside-nebula-js-extension-framework/td-p/2065737

**Comment by Caele** [comment]
Your extension should load what it needs and not rely on qlik sense to provide it. Any css loaded by the client might change, and specifically leonardo-ui is legacy code and will be removed.

The point of an external Extensions API such as Nebula is that we don't need to rely on the Sense code base to provide certain things, thus removing the need for loading all that code only to display a chart.

While there is some merit to adding external libraries to the serve command, this is not one of them.
