### ISSUE TITLE
Nebula Hub - connect to Qlik Cloud trial fails

### ISSUE THREAD

**Issue by jeff-1984** [qlik-oss/nebula.js#1450]
## 🐛 Bug report
I am trying to connect to my Qlik Cloud tenant (trial)
I added a web integration, with allowed origins : http://localhost:8000
=> In the nebula hub page : wss://[mytenant].eu.qlikcloud.com?qlik-web-integration-id=xxx+ connect
=> Result : infinite loop reloading the page at step 2 (select app)
I tried also with oauth "single page app", with user_default access rights, an error is returned by Qlik Cloud : 
{"errors":[{"title":"Invalid client_id","detail":"OAuth client is not authorized","code":"OAUTH-14","status":"400"}],"traceId":"0000000000000000d3a2403ffa24786d"}

It would be very nice to have a working step by step tutorial with the setup of the Qlik environement (Qlik Cloud and Qlik Sense). 
(is that not possible with Qlik Cloud trial ?)

Thanks

**Comment by Caele** [comment]
I've never tested a trial account, but I think it should work. 
The inifitely refreshing page sounds like an issue with the redirect URL, that you get an incorrect setup.
For reference, here are my oauth settings:
![Screenshot 2024-01-05 at 11 34 28](https://github.com/qlik-oss/nebula.js/assets/6318307/6f78fd63-c23a-4dd0-bb25-7ff6524dd897)

My engine URL is: wss://tenant.qlik-cloud.com/&qlik-client-id={myID}
