### ISSUE TITLE
Cant install initial dependencies

### ISSUE THREAD

**Issue by alan9518** [qlik-oss/nebula.js#1561]
## 🐛 Bug report

Using the command `npx @nebula.js/cli create hello --picasso none` as stated in the docs, nebula fails during the npm install process with 
unable to resolve dependency tree.using --force or --legacy-peer-deps flag not working either

Using a virtual machine with windows 11
node v18.20.3
npm v10.8.1

![image](https://github.com/qlik-oss/nebula.js/assets/13058957/8e7d3846-d7b2-496b-956e-b7552eb5b960)

### Steps to Reproduce

1. run npx @nebula.js/cli create hello --picasso none
2. run npm install after initial error message 
1. ...

### Expected behavior

Should be able to install dependencies to start working

### Actual behavior

can't install dependencies "@nebula.js/cli-build@undefined"

### Versions

- nebula.js: (5.1.2)
- Platform: ?
- Browser: ?

### Additional context

(Add any other context, link to demo or screenshots about the issue.)

**Comment by Caele** [comment]
There was a dependency issue in 5.1.2 that has since been resolved.
