### ISSUE TITLE
Listbox crashing when flags is undefined

### ISSUE THREAD

**Issue by haxxmaxx** [qlik-oss/nebula.js#1571]
## 🐛 Bug report
when using stardust to render the listbox, it can crash when `flags` is undefined. This can easily be solved 

### Steps to Reproduce

1. Use stardust for your mashup to render the selection toolbar
2. open a listbox

### Expected behavior

There should be no crash

### Actual behavior

The 

### Versions

- nebula.js: 5.2.0
- Platform: ?
- Browser: ?

### Additional context

Originally reported here 
https://github.com/qlik-oss/sn-list-objects/issues/443

**Comment by M1CK431** [comment]
ℹ️ Downgrading to v5.1.x "solve" the issue so we can be sure it's introduced in v5.2.0.
