### ISSUE TITLE
Bundle property not showing in the qext file

### ISSUE THREAD

**Issue by francisco-perez-qlik** [qlik-oss/nebula.js#1584]
## 🐛 Bug report

When adding bundle property to the meta.json file, that property doesn't go to the .qext file when making the build.

### Steps to Reproduce

1. Add the following to the meta.json:
```
"bundle": {
        "id": "testId",
        "name": "Test Name",
        "description": "test description"
  }
```

2. run `npm run build`
3. run `npm run sense`
4. check the .qext file

### Expected behavior

It was expected that the bundle property was in the .qext file

### Actual behavior

Bundle property doesn't go to the .qext file

### Versions

- nebula.js: 5.3.0

### Additional context

To solve this problem temporarily I created a script. But I wanted to know if this is a bug or the bundle property is deprecated.

**Comment by Caele** [comment]
Thank you for the question:
Nebula sense does not support the qext bundle property, it simply doesn't include as can be seen here:
https://github.com/qlik-oss/nebula.js/blob/main/commands/sense/lib/build.js#L38
I don't believe the bundle properties are officially supported (even if they are used internally and externally), which is likely why they where not included here.

We could possibly extend this to populate the qext with all meta fields, but it would make things a bit less robust. We might take a look at this down the line, but its not a pressing issue.
