### ISSUE TITLE
Unable to Use Master Measures/Dimensions in Nebula.js Charts

### ISSUE THREAD

**Issue by vighneshh** [qlik-oss/nebula.js#1632]
I'm using Nebula.js to create charts, and while I can create them with fields, I don't see any option or documentation to create chart like KPI, bar , line charts using Master Measures or Master Dimensions.

**Comment by T-Wizard** [comment]
have you tried something like this:
```javascript
// render on the fly
n.render({
  element: el,
  type: 'barchart',
  fields: ['Product', { qLibraryId: 'u378hn', type: 'measure' }]
});
```
that should use the master measure with id `u378hn`
(example taken from https://qlik.dev/apis/javascript/nebula-js/#definitions-embed-entries-render)
