### ISSUE TITLE
Add support for Gauge chart

### ISSUE THREAD

**Issue by cguinard-fbx** [qlik-oss/nebula.js#1652]
## 🚀 Feature

Add support for Gauge chart

### Motivation

Gauge chart is one of the most basic visualization types and also one of the most impactful, and thus it is widely used!

### Additional context

My use case is the following: I am using the qlik-embed react library to embed Qlik sheets and objects in a React application.
My sheet currently contains several gauges, and they are displayed as "Unknown chart: gauge" while the rest of the objects render as expected.

I discovered that this is because the Gauge chart type is not yet supported by nebula: https://qlik.dev/embed/qlik-embed/quickstart/qlik-embed-webcomponent-quickstart/ ==> redirects to https://qlik.dev/extend/extend-qlik-visualizations/supported-charts/

**Comment by Caele** [comment]
Hey, thanks for the ask, this is not an issue of Nebula itself, rather a priority of Qlik. We do have it on our radar, but I cannot promise any timeline.
I will relay this to product management, but I'd also ask you to check with your contact at qlik and make a formal request there.

**Comment by cguinard-fbx** [comment]
Hi @Caele , Thank you for your prompt answer, I will contact Qlik support to submit that requests.
