### ISSUE TITLE
Export image

### ISSUE THREAD

**Issue by miralemd** [qlik-oss/nebula.js#26]
### Motivation

Exporting images is important for reporting.

### Solution

A minimal nodejs service that:
- would receive a snapshot from the client
- render the snapshot using headless Chrome

### Concerns

Using headless Chrome requires Chrome to be installed on the machine running the service.

The mashup developer would be responsible for running the service.

**Comment by goldbergjeffrey** [comment]
what about using: https://github.com/microsoft/playwright/
