### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by miralemd** [qlik-oss/nebula.js#30]
The hooks concept introduced by React could be very fitting to use since a component in supernova is very similar in terms of lifecycle. Custom hooks could easily be shared for reusability and increased productivity.

Example hooks:

- `useState` to handle state (same as React)
- `useLayout` to consume a layout
- `useModel` to access the current object's enigma model
- `useApp` to access the app model
- `useTheme` to consume a theme
- `useResize` to handle a resize

```js
import { useLayout, useResize } from '@nebula.js/supernova'

export default function() {
  {
    qae: { /* */ },
    component() {
      const [state, setState] = useState({});
      const [layout] = useLayout();
      useResize(() => { /* do stuff on resize */ });

      // render stuff
    }
  }
}
```

**Comment by devisscher** [comment]
Example from useHooks.com https://usehooks.com/useWindowSize/
