### ISSUE TITLE
NPM install throwing gyp erros

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/nebula.js#342]
## 🐛 Bug report

When running npm install @nebula.js/cli@next -g receives this error in terminal
![image](https://user-images.githubusercontent.com/8709292/76248596-04f31c80-6218-11ea-90fd-78750f59af48.png)

### Steps to Reproduce

1. Open terminal in Mac
2. run npm install @nebula.js/cli@next -g

### Expected behavior

clean install

### Actual behavior

see screenshot: 
![image](https://user-images.githubusercontent.com/8709292/76248679-2c49e980-6218-11ea-8c1a-b3fe80c9ae33.png)

### Versions

- nebula.js: 0.2.0-alpha.1
- Platform: Mac
- Browser: ?

### Additional context

None.

**Comment by nilzona** [comment]
This happens sometimes. Try opening xcode, sometimes it installs additional packages upon opening after updates. If error still remains try this:
