### ISSUE TITLE
Does not render in Safari

### ISSUE THREAD

**Issue by AnalyticsEarth** [qlik-oss/nebula.js#343]
## 🐛 Bug report

When running the sample template and editing the Picasso specification, rendering is not updating properly to the size of the window in Safari browser. The same code works fine in Chrome.

Also the code settings and previews don't work and produce blank screens in the browser.

### Steps to Reproduce

1. Create Nebula project
1. Open in Safari
1. Open Settings (get blank screen)
1. Edit hypercube and main chart area does not update to the correct result. The screen does not update when browser is changed in size.

### Expected behavior

The chart should be shown and displayed the same as it does in Chrome.

### Actual behavior

Incorrect chart rendering or blank screen.

### Versions

- nebula.js: 0.2.0-alpha.1
- "@nebula.js/supernova": "^0.1.0-alpha.28"
- Platform: Mac OS
- Browser: Safari

### Additional context

(Add any other context, link to demo or screenshots about the issue.)

**Comment by scotthsieh0503** [comment]
Just wondering it's closed because this issue was fixed in a later release? 
I am currently experiencing something.

**Comment by Caele** [comment]
@scotthsieh0503  As this was filed on an old version I did some quick tests in Safari and couldn't reproduce it. If you see any anything please open a new issue and we'll take a look.
