### ISSUE TITLE
Nebula Qlik Sense 

### ISSUE THREAD

**Issue by JuanCla13** [qlik-oss/nebula.js#436]
## 🐛 Bug report

I'm trying to export a nebula visualization into Qlik Sense using cmd command sense, but when I copy the files into extensions directory of Qlik Sense Desktop and then run the extension, the extension doesn't show anything.

### Steps to Reproduce

1. cmd command --> sense in my nebula visualization
2. copy the .js, .qext and dist files into extensions directory
3. run the extension in Qlik Sense Desktop

### Expected behavior

Plot de visualization correctly 

### Actual behavior

The extension doesn't show the data.

### Versions

- nebula.js: (0.6.0)
- Platform: Qlik
- Browser: Chrome

### Additional context
This is a simple hypercube visualization in nebula.

![Captura de pantalla (46)](https://user-images.githubusercontent.com/57191997/83395095-ffae0400-a3f9-11ea-8a94-f8a3a257bca4.png)

And when I try to export into Qlik Sense

![Captura de pantalla (49)](https://user-images.githubusercontent.com/57191997/83395368-70552080-a3fa-11ea-926b-f75dee6fcad5.png)

**Comment by miralemd** [comment]
Hi @JuanCla13 ,

The sense command currently works for QCS only and will work for Qlik Sense Enterprise/Desktop as of June 2020 - we are considering enabling it so that it works on older Sense versions, which version are you on?

**Comment by JuanCla13** [comment]
Hi @miralemd ,

My Qlik Sense Desktop version is from february 2020, should I update it to the latest aviable?

**Comment by miralemd** [comment]
You can try QCS, or wait a few days until we have the command work on older Sense versions

**Comment by JuanCla13** [comment]
Thanks for your response!

**Comment by miralemd** [comment]
Fixed as of v1.0.0
