### ISSUE TITLE
Picasso template does not destroy pic

### ISSUE THREAD

**Issue by KFredberg** [qlik-oss/nebula.js#47]
## 🐛 Bug report
Picasso template does not call pic.destroy

### Expected behavior
Creating a new picasso template shall call the `pic.destroy` on the life cycle hook `destroy`.
### Versions

* nebula.js: (0.1.0-alpha.13)

### Additional context
https://github.com/qlik-oss/nebula.js/blob/master/packages/create/generator/templates/project/supernova.ejs#L37

**Comment by miralemd** [comment]
fixed by #288
