### ISSUE TITLE
sn-sankey-chart does not work

### ISSUE THREAD

**Issue by fkabinoff** [qlik-oss/nebula.js#503]
## 🐛 Bug report

sn-sankey-chart does not work. Error in console is "Error: Invalid stardust hook call. Hooks can only be called inside a visualization component."

### Steps to Reproduce

1. Start a new web project with `npx @nebula.js/cli create mashup`
2. Install @nebula.js/sn-pie-chart in project with `npm install --save @nebula.js/sn-sankey-chart`
3. Configure connection, register sn-sankey-chart as a type, and try to render a sankey chart visualization

### Expected behavior

Render a sankey chart.

### Actual behavior

Sankey chart not rendered. Error in console is "Error: Invalid stardust hook call. Hooks can only be called inside a visualization component."

### Versions

- nebula.js/stardust: 1.0.0 
- nebula.js/sn-sankey-chart: 0.4.1
- Platform: Windows
- Browser: Chrome

**Comment by miralemd** [comment]
Duplicate https://github.com/qlik-oss/nebula.js/issues/488
