### ISSUE TITLE
sn-funnel-chart does not work

### ISSUE THREAD

**Issue by fkabinoff** [qlik-oss/nebula.js#504]
## 🐛 Bug report

sn-funnel-chart does not work. Error in console is "Error: Invalid stardust hook call. Hooks can only be called inside a visualization component."

### Steps to Reproduce

1. Start a new web project with `npx @nebula.js/cli create mashup`
2. Install @nebula.js/sn-funnel-chart in project with `npm install --save @nebula.js/sn-funnel-chart`
3. Configure connection, register sn-funnel-chart as a type, and try to render a funnel chart visualization

### Expected behavior

Render a funnel chart.

### Actual behavior

Funnel chart not rendered. Error in console is "Error: Invalid stardust hook call. Hooks can only be called inside a visualization component."

### Versions

- nebula.js/stardust: 1.0.0 
- nebula.js/sn-funnel-chart: 0.3.4
- Platform: Windows
- Browser: Chrome

**Comment by miralemd** [comment]
Duplicate https://github.com/qlik-oss/nebula.js/issues/488
