### ISSUE TITLE
Browser warning about non-passive event listeners

### ISSUE THREAD

**Issue by countnazgul** [qlik-oss/nebula.js#507]
## 🐛 Bug report

When I'm including nebula charts (in my case bar and pie charts) im getting a warning messages in the console about adding non-passive event listeners for a 'wheel' event (see screenshot below). Not that its a big deal but its annoying :)

### Expected behaviour

No warning messages (if possible)

### Versions

- nebula.js:
    "@nebula.js/sn-bar-chart": "^0.3.1",
    "@nebula.js/sn-pie-chart": "^0.3.3",
    "@nebula.js/stardust": "^1.0.0",
- Platform: Windows 10
- Browser: Chrome 85.0.4183.83

### Additional context

(Add any other context, link to demo or screenshots about the issue.)
![image](https://user-images.githubusercontent.com/22850/92656852-b10ee080-f2eb-11ea-81ff-7ebe793a7f06.png)

**Comment by Caele** [comment]
This has been passed on to the chart devs.

**Comment by countnazgul** [comment]
Thanks!
