### ISSUE TITLE
Loading Nebula.js into Salesforce Lightning Web Components 

### ISSUE THREAD

**Issue by atnmorrison** [qlik-oss/nebula.js#509]
## 🐛 Bug report

I'm trying to load Nebula.js into a Salesforce Lightning Web Component. Salesforce forces LWC components and libraries that get loaded in to run in strict mode. In the source code for nebula.js there is this comment:

"If  you've misconfigured your bundler to force strict mode and applied a  CSP to forbid Function, and you're not willing to fix either of those problems, please detail your unique predicament in a GitHub issue." 

I'm not using a bundler, I'm just trying to load the library in as a commonjs module which is all I can do with lightning web components and I don't have control of salesforce so am unable to load the library in without strict mode so I end up in the "accidentalStrictMode" code that calls Function which seems to run fine but then Salesforce throws an error loading the library that says "regeneratorRuntime" is undefined 

### Steps to Reproduce

1. Download the library
2. Upload to salesforce as a static resource 
3. Create a lightning web component 
4. Try and load the library with the following  code

import nebula from '@salesforce/resourceUrl/nebula'

loadScript(this, nebula).then(async () => {
  console.log('nebula script loaded');
});

### Expected behavior

Script loads into lightning web component successfully 

### Actual behavior

Script fails to load with error:

WARNING: Failed to load script at /resource/1600166075000/qfw__nebula: regeneratorRuntime is not defined [regeneratorRuntime is not defined]

### Versions

- nebula.js: (0.6.0)
- Platform: Salesforce
- Browser: Chrome

### Additional context

I was able to load enigma and open a websocket to QSE SaaS app succesfully from the lightning web component, now I want to render a visualization from the qlik sense app using nebula without using an iframe which works but is not ideal    

https://salesforce.stackexchange.com/questions/319637/load-scripts-in-lightning-web-component-with-out-strict-mode/319650#319650

**Comment by miralemd** [comment]
Hi @atnmorrison ,

Not sure what you mean with 

>  In the source code for nebula.js there is this comment: "If you've misconfigured your bundler ...

since there's no such thing in nebula.js.

regeneratorRuntime is bundled with nebula.js 1.0.0, you should try using that version instead of the pre-stable 0.6.

**Comment by atnmorrison** [comment]
I might have the wrong project, I'm using the development library link here 

https://qlik.dev/libraries-and-tools/nebulajs/installation

**Comment by atnmorrison** [comment]
added var regeneratorRuntime; to line 13 which fixes the issue loading the library int LWC
