### ISSUE TITLE
Add useRef hook export

### ISSUE THREAD

**Issue by yianni-ververis** [qlik-oss/nebula.js#510]
## 🚀 Feature

https://reactjs.org/docs/hooks-reference.html#useref

### Motivation

Needed for custom extensions like sn-table

### Additional context

(Add any other context or screenshots about the feature request.)

**Comment by miralemd** [comment]
@yianni-ververis Can you provide a little more context and how you would use this?

**Comment by yianni-ververis** [comment]
const tableRef = useRef();

      const onScroll = event => {
        const scrollPosition = tableRef.current.scrollTop;
        const tableHeight = tableRef.current.offsetHeight;
        const tableInnerHeight = tableRef.current.children[0].offsetHeight;
        ....
      }

      return (
          ...
          <TableContainer style={{ height, overflow: 'auto' }} ref={tableRef}>

**Comment by miralemd** [comment]
Ok, that would mean exposing React's API and creating a dependency on a 3rd party API which is not something we want to do in nebula.js.
