### ISSUE TITLE
Bar chart  possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by arperyan** [qlik-oss/nebula.js#511]
## 🐛 Bug report

After creating a bar chart after destroying, I get the following error in the console: **stardust.dev.js:1694 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.**

### Steps to Reproduce

1. Create bar chart
2. Destroy bar chart
3. create new bar chart

### Expected behavior

No error - I don't get this error for a pie chart

### Actual behavior

errormessage

### Versions

- nebula.js: "@nebula.js/stardust": "^1.0.1", "@nebula.js/sn-bar-chart": "^0.7.0",
- Platform: windows
- Browser: chrome

### Additional context

![image](https://user-images.githubusercontent.com/20163734/94259257-1850a580-ff26-11ea-96cb-bd8247bd52f2.png)

**Comment by Caele** [comment]
Thank you for your bug report. It has been passed along to the appropriate team to analyse as it is a bug in the barchart package and not nebula itself. Will likely keep this open for tracking purposes though.

**Comment by Caele** [comment]
Should be resolve in @nebula.js/sn-bar-chart 0.7.2
