### ISSUE TITLE
tables?

### ISSUE THREAD

**Issue by QHose** [qlik-oss/nebula.js#525]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Hi,

I wondered why there are no table visualizations?

If someone want to embed that would be a first thing?

### Motivation

(A clear and concise description of why this feature should be added.)

### Additional context

(Add any other context or screenshots about the feature request.)

**Comment by Caele** [comment]
@QHose Yes, a table visualization using nebula would be nice, and one can question why there isn't one already. I cannot divulge any internal roadmaps, but I can say that it is not forgotten.
I do want to point out however that Nebula is not really where the Sense charts live, it is the framework/API used to enable them. So this is not the place for the table feature request, so I will note this and close it.
