### ISSUE TITLE
docs/sn-create.md: array elements for selectedRows must be number 

### ISSUE THREAD

**Issue by LiKang6688** [qlik-oss/nebula.js#569]
### Steps to Reproduce
In docs/sn-create.md, 
```
selections.select({
       method: 'selectHyperCubeCells',
       params: ['/qHyperCubeDef', selectedRows, []],
 });
```

### Expected behavior
Modal selection works.
<img width="159" alt="Screenshot 2021-02-03 at 11 39 38" src="https://user-images.githubusercontent.com/4471489/106735445-8879e100-6614-11eb-93be-918ec8845e86.png">

### Actual behavior
when I follow the example, selectedRows in the selections.select() is an array, such as ["1", "2"], the modal selection does not work. 
<img width="169" alt="Screenshot 2021-02-03 at 11 38 28" src="https://user-images.githubusercontent.com/4471489/106735294-58324280-6614-11eb-9572-99db782593f8.png">

<img width="724" alt="Screenshot 2021-02-03 at 11 29 30" src="https://user-images.githubusercontent.com/4471489/106734260-181e9000-6613-11eb-9555-ba99c7df7419.png">

Then I did an experiment and found that array elements for selectedRows must be number, such as [1, 2].
It is good that in the doc, we make sure that array elements for selectedRows are number instead of string.
### Versions

- nebula.js: (1.1.0-alpha0)
- Platform: MacOS
- Browser: Chrome

**Comment by arperyan** [comment]
HI @LiKang6688,

In the document sn-create, it states **const row = _+_e.target.parentElement.getAttribute('data-row');** . The + in front of a value will attempt to convert it to a number?

Ryan Arpe

**Comment by LiKang6688** [comment]
> HI @LiKang6688,
> 
> In the document sn-create, it states **const row = +e.target.parentElement.getAttribute('data-row');** . The + in front of a value will attempt to convert it to a number?
> 
> Ryan Arpe

I see. You are right! Thank you, Ryan.
