### ISSUE TITLE
Color utilities to handle color expressions

### ISSUE THREAD

**Issue by haxxmaxx** [qlik-oss/nebula.js#577]
## 🚀 Feature

Logic to resolve color expressions. Already used in multiple agnostic charts (sn-action-button, sn-org-chart) by having duplicate code in those repos.
### Motivation

Much cleaner to have the logic in nebula. One source also ensures consistent behaviour across different charts. I just copy pasted the code into the sn-table as well.
### Additional context

This is one place where `resolveExpression` is defined. `isDarkColor` is needed in the table now as well.
https://github.com/qlik-oss/sn-org-chart/blob/master/src/utils/color-utils.js.

**Comment by Caele** [comment]
Resolved by #1396
