### ISSUE TITLE
Populate property definition with object list from useApp hook

### ISSUE THREAD

**Issue by Marnnn** [qlik-oss/nebula.js#598]
## 🚀 Feature

Ability to utilise useApp hook from supernova component when building the property definition in extDefinition.js. This will allow for app objects such as sheets and master items to be available as options within the dropdown property component.

### Motivation

It's a common pattern I've used in traditional Qlik Sense extensions, one use case is for building a custom navigation component which allows for sheets to be selected as dropdown component properties. Another would be for a card style extension where you want to include different charts/objects created and added as master items onto cards.

### Additional context

Here is an example of a getSheets function using the useApp hook.
```javascript
component() {
      const el = useElement();
      const layout = useLayout();
      const app = useApp();

      const getSheets = () => {
        return app.getAllInfos().then(infos => {
            return infos.filter(infoItem => infoItem.qType === 'sheet').map(sheet => {
              const item = {
                value: sheet.qId
              }
              
              app.getObject(sheet.qId).then(obj => {
                  return obj.getLayout().then(objLayout => {
                    item.label = objLayout.qMeta.title
                  })
              })
              return item
            })
        })
      }
```
Example of the dropdown property using the function.
```javascript
SheetDropdown: {
  type: "string",
  component: "dropdown",
  label: "Select a sheet",
  ref: "pages.sheetDropdown",
  options: getSheets()
}
```
I have tried a few different ways to build the extDefinition object, first I just tried to import the useApp hook from stardust but it errored saying it can only be used inside a supernova component. I then tried creating a supernova component that exported a property definition object, but I'm not sure the nebula sense build script knew what to do with it, it compiled ok and no errors but it didn't work.

Any ideas on how to get this working would be great or if it's even doable? I wasn't sure to put this as a bug or a feature as it's probably more of a request for help!

**Comment by T-Wizard** [comment]
using useApp hook (or any other hook) in the the property definition is not possible.

But in any Qlik Sense extensions, (including one created by using supernova)
the options in a dropdown property panel definition can be a function (that returns the options list, or a promise of it)
it will get three arguments and the thrid one has an app property with the app.
(I don't know if this is part of officially supported part of the property panel api, but it is probably stable enought for use)

```
SheetDropdown: {
  type: "string",
  component: "dropdown",
  label: "Select a sheet",
  ref: "pages.sheetDropdown",
  options: (data, handler, context) => context.app.getAllInfos().then(...)
}
```

**Comment by Caele** [comment]
Thank you for your suggestion, we will absolutely take an extra look at this.
@T-Wizard s explanation is the current way to do this, but it is a bit of an unsupported api.

What we currently support is the `nebula sense` build (https://github.com/qlik-oss/nebula.js/tree/master/commands/sense) which wraps you Nebula chart in the old extensions API, allowing for usage in most versions of Sense.
What we aim to do is let you import the Nebula chart directly, currently in an experimental stage, but can be seen in for example the Nebula table: https://github.com/qlik-oss/sn-table, where it uses the flag `supernova: true` in the .qext to tell the client that it is a Nebula chart. More to come on this.

**Comment by Marnnn** [comment]
@T-Wizard you absolute legend! I never new that was there, I've actually used the first two as found them in various examples over time.

@Caele Thank you, yes I'll use T-Wizard's suggestion as I'm already using functions as options with the data argument so fits in nicely. That sounds interesting! I'm excited to build some more extensions using Nebula and will look out for updates!

**Comment by Caele** [comment]
Closing this as we've added some documentation at least: https://qlik.dev/libraries-and-tools/nebulajs/in-qlik-sense
We have no full resolution for this particular issue yet, it likely would mean more documentation to clarify the solution mentioned here.
