### ISSUE TITLE
Add options to the internal listbox

### ISSUE THREAD

**Issue by MarkFereday** [qlik-oss/nebula.js#668]
## 🚀 Feature

Using the internal listbox to present a field filter has no options for e.g. sorting

### Motivation

A very common use-case in a mashup, add filters with a defined sort, or a sort changeable by the user

### Additional context

Raised on QlikBranch, recommended to raise as issue here.  See also https://github.com/qlik-oss/nebula.js/pull/654

**Comment by Caele** [comment]
This should work for you for now:
```
nebbie.field('[My Field]').then((s) =>
      s.mount(document.querySelector('.listbox'), {
        properties: {
          qListObjectDef: {
            qDef: {
              qSortCriterias: [
                {
                  qSortByState: 0,
                  qSortByAscii: 1,
                  qSortByNumeric: 1,
                  qSortByLoadOrder: 1,
                },
              ],
            },
          },
        },
      })
    );
```
Will keep this open as the current solution requires very intimite knowledge of the hyperCube properties. Sorting should be simpler.

**Comment by MarkFereday** [comment]
I'll try this ASAP

**Comment by Caele** [comment]
Closing as no more work on options are planned, will instead point to the coming filterpane chart.
