### ISSUE TITLE
halo.app.getObject is not a function

### ISSUE THREAD

**Issue by gangataarun** [qlik-oss/nebula.js#670]
Hi,

I'm trying to embed a simple visualisation from qliksense saas. I have authenticated using the web integration and can connect the engine using Engima.Js. I would like to embed an visualisation into my React app.  I am getting the error "**halo.app.getObject is not a function**" when I run the getobject function in EngimaJS it returns the objects response.

below is code in react

```
import { Typography } from "@material-ui/core";
import { embed } from "@nebula.js/stardust";
import React, { useEffect } from "react";
import enigmaService from "./engima";

const NebulaTest = () => {
  useEffect(() => {
// returns the app. The app is opened and stored in enigmaService. the promise response is correct
    let app = enigmaService.getapp(); 
    let n = embed(app);
    n.render({
      element: document.querySelector("#xXWqHy"),
      id: "xXWqHy"
    });
    console.log(app);
  }, []);

  return (
    <div>
      <Typography>Noob see if this works</Typography>
      <div id="xXWqHy" />
    </div>
  );
};

export default NebulaTest;
```

![image](https://user-images.githubusercontent.com/19910129/132217481-a0e4ca7e-3bca-4cab-9387-66a16102a099.png)

**Comment by arperyan** [comment]
Hi,

Please provide the code for your enigma.js file?

Ryan Arpe

**Comment by gangataarun** [comment]
Hey @arperyan,

Please see code for engima below

````
import enigma from "enigma.js";
import schema from "enigma.js/schemas/12.170.2";

const webIntegrationId = "xxxxxxxx";

const hosturl = "https://xxxxxxx.eu.qlikcloud.com";
var clienthost = "https://xxxxx.csb.app";
var appid = "xxxxxxx";

class EnigmaService {
  qix = null;
  document = null;
  prevSelections = null;
  static instance = null;
  csrftoken = null;

  async connect() {
    var reuurl = hosturl + "/api/v1/audits";

    await fetch(reuurl, {
      method: "GET",

      credentials: "include",
      headers: {
        "Qlik-Web-Integration-ID": webIntegrationId
      }
    })
      .then(function (response) {
        if (response.status === 401) {
          const url = new URL(`${hosturl}/login`);
          url.searchParams.append("returnto", clienthost);
          url.searchParams.append("qlik-web-integration-id", webIntegrationId);
          window.location.href = url;
          //return 1;
        }
        return response.json();
      })
      .then(function (result) {
        return true;
      })
      .catch(function (error) {
        return false;
      });
  }


  async init() {
    await this.connect();
    // fetches the token and this is working
    var token = await this.getcsfrtoken();

    const url =
      "wss://" +
      "rmgtest.eu.qlikcloud.com" +
      "/app/" +
      appid +
      "?qlik-web-integration-id=" +
      webIntegrationId +
      "&qlik-csrf-token=" +
      token;
    console.log(url);
    const session = enigma.create({
      schema,
      url
      //suspendOnClose: true,
    });



    this.qix = await session.open();

    this.document = await this.qix.openDoc(appid);

    console.log(this.document.getAppLayout());
    return this.document;
  }

  async getapp() {
   return this.document;
  }




  static createInstance() {
    const object = new EnigmaService();
    return object;
  }

  static getInstance() {
    if (!EnigmaService.instance) {
      EnigmaService.instance = EnigmaService.createInstance();
    }

    return EnigmaService.instance;
  }
}

const enigmaService = EnigmaService.getInstance();
export default enigmaService;
```
`

**Comment by T-Wizard** [comment]
as getapp is marked as async it will return a promise of an app but embed expect just an app.
try removing the async from the getapp definition. (If you have code that wait for init to be done before NebulaTest it can work.)

**Comment by gangataarun** [comment]
@T-Wizard 
I'm getting this issue now. Could you please help?
![image](https://user-images.githubusercontent.com/19910129/132225691-1d15b9a0-eb64-4be6-833c-c972b927c2a0.png)

**Comment by T-Wizard** [comment]
You also need to register the object types you want to use in nebula.js
see: https://qlik.dev/tutorials/build-a-simple-mashup-using-nebulajs#more-types for an example of registering piechart
In this case it looks like you are trying to render an container object and that is not included in the [list of supported charts](https://qlik.dev/libraries-and-tools/nebulajs/supported-charts).

**Comment by gangataarun** [comment]
@T-Wizard 
I changed it to a bar chart and I'm getting the same issue
![image](https://user-images.githubusercontent.com/19910129/132228482-d9f19f4f-f92e-4821-ab63-e7b2c0a726c2.png)

**Comment by arperyan** [comment]
Hi,

```import bar from "@nebula.js/snbar-chart"
let n = embed(app, {
types: [
      {
        name: "barchart",
        load: () => Promise.resolve(bar)
      },

});```

**Comment by gangataarun** [comment]
Hi @arperyan , 
Thank you. That has worked. How can I use the same colours in the object as is in the dashboard?

**Comment by arperyan** [comment]
{
  themes: [{
    id: 'pinkish',
    load: () => Promise.resolve({
      palettes: {
        data: [{
          scale: [
            '#fac6e5',
            '#ff95d6',
            '#e76eb1',
            '#b44772',
          ],
        }]
      }
    })
  }],
  context: {
    theme: 'pinkish'
  }
};

See https://qlik.dev/libraries-and-tools/nebulajs/configuration

**Comment by Caele** [comment]
Closing this as it isn't really a bug.
