### ISSUE TITLE
Scale Break across barchart when there is extreme large values

### ISSUE THREAD

**Issue by marvelvv** [qlik-oss/nebula.js#704]
## 🚀 Feature

A scale break feature on the barchart to demonstrate some values are extreme higher than others

### Motivation

There are business cases that the dataset varies widely, e.g. $ sales may range between 1 and 10000000000000.
In order to compare the relevance of several sales team, under extreme case, Team A sold $1 products, Team B sold $10 products while Team C sold $100B products, a break across bars will showcase the Team C is way much higher than the rest.

### Additional context

A break across the bar and/or the y-axis, such as...
https://docs.microsoft.com/en-us/sql/reporting-services/report-design/add-scale-breaks-to-a-chart-report-builder-and-ssrs?view=sql-server-ver15

**Comment by Caele** [comment]
Closing as not planned.
