### ISSUE TITLE
storybook does not work

### ISSUE THREAD

**Issue by LiKang6688** [qlik-oss/nebula.js#835]
## 🐛 Bug report

(A clear and concise description of what the bug is.)

### Steps to Reproduce

1. yarn start:ui

### Expected behavior

(A clear and concise description of what you expected to happen.)

### Actual behavior

(A clear and concise description of what actually happened.)
<img width="896" alt="Screenshot 2022-05-26 at 15 36 13" src="https://user-images.githubusercontent.com/4471489/170498852-74fa2ac1-bf45-4ad3-b08c-3bef4161f492.png">

### Versions

- nebula.js: (x.y.z)
- Platform: ?
- Browser: ?

### Additional context

(Add any other context, link to demo or screenshots about the issue.)

**Comment by Caele** [comment]
duplicate #800
