### ISSUE TITLE
CI:  ls cannot access 'node_modules/@nebula.js': No such file or directory

### ISSUE THREAD

**Issue by LiKang6688** [qlik-oss/nebula.js#890]
## 🐛 Bug report

In the circle ci, ls: cannot access 'node_modules/@nebula.js': No such file or directory in 'Create Nebula visualization project: Mashup in hello-mashup'

### Actual behavior

https://app.circleci.com/pipelines/github/qlik-oss/nebula.js/4984/workflows/8075751f-1e0a-46b3-91e9-bb313ab37826/jobs/7006/steps

<img width="1004" alt="Screenshot 2022-07-26 at 11 01 55" src="https://user-images.githubusercontent.com/4471489/180968816-4dd77744-f339-4a6b-a5c7-5c5ae791aa59.png">

### Versions

- nebula.js: (x.y.z)
- Platform: ?
- Browser: ?

### Additional context

(Add any other context, link to demo or screenshots about the issue.)

**Comment by T-Wizard** [comment]
there is an earlier error on line 27: `error Couldn't find any versions for "@nebula.js/stardust" that matches "3.0.0-alpha11"`

**Comment by LiKang6688** [comment]
> there is an earlier error on line 27: `error Couldn't find any versions for "@nebula.js/stardust" that matches "3.0.0-alpha11"`

I see. Thank you @T-Wizard. Now it is available.
