### ISSUE TITLE
Error when trying to install latest version of nebula CLI

### ISSUE THREAD

**Issue by linhnguyen-qlik** [qlik-oss/nebula.js#900]
## 🐛 Bug report

I tried to install nebula CLI with this command `npx @nebula.js/cli create hello --picasso none ` and I got the below error.

![Screenshot 2022-08-24 at 13 42 49](https://user-images.githubusercontent.com/111750285/186409913-449a2979-dc25-4aa0-9ea1-fd2612e133e6.png)

### Steps to Reproduce

1. In terminal run `npx @nebula.js/cli create hello --picasso none`
1. Press "y" when being asked "Ok to proceed?"

### Expected behavior

To install successfully and create a project folder called hello.

### Actual behavior

Fail to install and no project folder created.

### Versions

- nebula.js:  @nebula.js/cli@3.0.0-alpha13
- Platform: Mac
- Browser: Chrome

### Additional context

Installing `@nebula.js/cli@2.13.0` worked.

**Comment by LiKang6688** [comment]
Replace  `'^3.x'` with `'^3.0.0-alpha'`

**Comment by johanlahti** [comment]
I cloned the Nebula.js repo, did the above and yarn link:ed it to my other repo (`yarn link` + `yarn link "@nebula.js/cli"`). Then I was able to run my command:
```
npx @nebula.js/cli create my-viz-name --pkgm npm --picasso none
```
