### ISSUE TITLE
Dependency tree error between latest stardust (3.0.0-rc.2) and sn-kpi (or sn-bar-chart, sn-combo-chart)

### ISSUE THREAD

**Issue by rkassoss** [qlik-oss/nebula.js#918]
## 🐛 Bug report

Got some dependency tree error between 'stardust' and the specific charts I am trying to install.

### Steps to Reproduce

1. installed stardust - npm install @nebula.js/stardust
2. tried to install sn-kpi - npm install @nebula/sn-kpi

### Expected behavior

Being able to install and render with nebula charts

### Actual behavior

$ npm install @nebula.js/sn-kpi
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ng-cyber-index@0.0.0
npm ERR! Found: @nebula.js/stardust@3.0.0-rc.2
npm ERR! node_modules/@nebula.js/stardust
npm ERR!   @nebula.js/stardust@"^3.0.0-rc.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nebula.js/stardust@">=1.0.0" from @nebula.js/sn-kpi@0.9.1
npm ERR! node_modules/@nebula.js/sn-kpi
npm ERR!   @nebula.js/sn-kpi@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\cgu\AppData\Local\npm-cache\eresolve-report.txt for a full report.

 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cgu\AppData\Local\npm-cache\_logs\2022-09-07T18_20_55_538Z-debug-0.log

**Comment by Caele** [comment]
v3 now released, will resolve this.
