### ISSUE TITLE
Listbox search bar - can't type "space" key

### ISSUE THREAD

**Issue by rkassoss** [qlik-oss/nebula.js#960]
## 🐛 Bug report

Cannot type the "space" key into the search bar. You can copy and paste a string with space characters, but can't type it.

### Steps to Reproduce

1. Click on the search bar
2. Type "John Doe"

### Expected behavior

Should see "John Doe" string presented in the search bar and value list filtered down only to "John Doe" and it is highlighted in yellow.

### Actual behavior

"JohnDoe" is typed in the search bar and there are no values meeting that search criteria

### Versions

- @nebula/stardust - 3.0.1
- Platform: Qlik Sense Enterprise on Windows - Feb 2022
- Browser: Chrome, Edge

### Additional context

(Add any other context, link to demo or screenshots about the issue.)
![listbox-searchbar-issue-1](https://user-images.githubusercontent.com/11234344/195190831-8044ed06-0516-45a3-8e63-ae4adf82fdbb.PNG)

**Comment by Caele** [comment]
Confirmed, the event ends up in here: https://github.com/qlik-oss/nebula.js/blob/master/apis/nucleus/src/components/listbox/interactions/listbox-keyboard-navigation.js#L87
Even if you are already focusing the input field itself.
